Models/Modulo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Models
{
    public class Modulo
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }
        public string? Usuario { get; set; }
    }
}

Models/Turno.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Models
{
    public class Turno
    {
        [Key]
        public int Id { get; set; }
        public string Categoria {get; set;}
        public string TipoDocumento {get; set;}
        public string Identificacion {get; set;}
        public string Ficho {get; set;}
        public DateTime FechaEntrada {get; set;}
        public DateTime? FechaAtendido {get; set;}
        public DateTime? FechaSalida {get; set;}
        public string Estado {get; set;}

        // [ForeignKey ("Modulos")]
        // public int IdModulo { get; set; }


        
    }
}

Controllers/ReceptionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Models;

namespace Turnero.Controllers
{
   
    public class ReceptionController : Controller
    {
        private readonly TurnosContext _context;

        public ReceptionController(TurnosContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Login = HttpContext.Session.GetString("Nombre");

            ViewBag.Modelos = await _context.Modulos.ToListAsync();
            var result  = await _context.Turnos.ToListAsync();


            ViewBag.TotalPen = result.Where(e=> e.Estado.Equals("Pendiente")).Count();
            // ViewBag.Categorias = result.Where(e => e.Estado == "En Espera").Select(c => new {c.Categoria}).GroupBy(e=> e.Categoria).Count();
            ViewBag.Categorias = result.Where(t => t.Estado.Equals("Pendiente"))
                                        .GroupBy(t => t.Categoria)
                                        .Select(g => new { Categoria = g.Key, Total = g.Count() })
                                        .ToList();
            
            return View();
        }


        public async Task<IActionResult> Create(Recepcion usuario){

            Recepcion newUser = new Recepcion{
                Nombre = usuario.Nombre,
                Correo = usuario.Correo,
                Password = BCrypt.Net.BCrypt.HashPassword(usuario.Password),//Encryptar la contraseña
                FechaRegistro = DateTime.Now
            }; 

            /* return Json(newUser); */

            await _context.Usuarios.AddAsync(newUser);
            _context.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        public async Task<IActionResult> Turnos()
        {
            ViewBag.Login = HttpContext.Session.GetString("Nombre");
            return View(await _context.Turnos.ToListAsync());
        }

          public async Task<IActionResult> Atencion()
        {
            ViewBag.Login = HttpContext.Session.GetString("Nombre");
            
            return View(await _context.Turnos.Where(t => t.Estado.Equals("En Espera")).ToListAsync());
        }


        public async Task<IActionResult>Modulos()
        {
            ViewBag.Login = HttpContext.Session.GetString("Nombre");
            
            return View(await _context.Modulos.ToListAsync());
        }

         public async Task<IActionResult>Usuarios()
        {
            ViewBag.Login = HttpContext.Session.GetString("Nombre");
            
            return View(await _context.Usuarios.ToListAsync());
        }

        
    }
}

Views/Reception/Atencion.cshtml
@{
    ViewData["Title"] =  "Atencion";
}

<div class="container">
    <div class="row">
        <div class="d-flex">
            <div class="col float-end">
                <a asp-controller="Reception" asp-action="Index">Regresar</a>
            </div>
        </div>
    </div>
    <div class="row">
        <h1>Modulo: </h1>
    </div>
    <div class="row">
        <div class="col-md-5">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Categoria</th>
                        <th>Turno</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @{int countRecord = 1;}
                    @foreach(var turno in Model){
                        <tr>
                        <td>@countRecord</td>
                            <td>@turno.Categoria</td>
                            <td>@turno.Ficho</td>
                            <td><a href="" class="btn btn-sm btn-primary">Llamar</a></td>
                        </tr>
                        countRecord++;
                    }
                </tbody>
            </table>

            <div class="row">
                <a href="" class="btn btn-lg btn-success">Llamar siguente</a>
            </div>
        </div>
        <div class="col-md-7">
            <h2>Turno en atención</h2>
            
            <div class="card text-center">
                <div class="card-body ">
                    <h3 class="card-title">IG-03</h3>
                    <p class="card-text">CC-120314</p>
                    <p class="card-text">CC-120314</p>
                </div>
                <div class="card-footer">
                    <a href="" class="btn btn-primary">Finalizar</a>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Reception/Index.cshtml
@{
    ViewData["Ttitle"] = "Home";
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="Item">
            <table class="table">
                <thead>
                    <tr >
                        <th colspan="2">Turnos Pendientes</th>
                    </tr>
                    <tr>
                        <th>Servicio</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    
                    @foreach(var item in ViewBag.Categorias){
                        <tr>
                            <td>@item.Categoria</td>
                            <td>@item.Total</td>
                        </tr>
                    }
                    <tr>
                        <th class="text-end">Total</th>
                        <th>@ViewBag.TotalPen</th>
                    </tr>
                </tbody>
            </table>
        </div>

        </div>
        <div class="col-md-6">
            <div class="grid-container">
                <div class="Item">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Usuarios</h3>
                        </div>
                        <div class="card-footer">
                            <a asp-controller="Reception" asp-action="Usuarios" class="btn btn-primary">Gestionar usuarios &rightarrow;</a>
                        </div>
                    </div>
                </div>
                <div class="Item">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Modulos</h3>
                        </div>
                        <div class="card-footer">
                            <a asp-controller="Reception" asp-action="Modulos" class="btn btn-primary">Gestionar Modulos &rightarrow;</a>
                        </div>
                    </div>
                </div>
                <div class="Item">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Turnos</h3>
                        </div>
                        <div class="card-footer">
                            <a asp-controller="Reception" asp-action="Turnos" class="btn btn-primary">Gestionar Turnos &rightarrow;</a>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2>Atender</h2>
                    <form asp-controller="Reception" asp-action="Atencion" method="post">
                        <div class="form-group">
                            <label for="">Modulo:</label>
                            <select name="" id="" class="form-control form-select">
                                @foreach(var modulo in ViewBag.Modelos){
                                <option value="@modulo.Id">@modulo.Nombre</option>
                            }
                                
                            </select>

                        </div><br>
                        <div class="form-group">
                                <button class="btn btn-success col-md-6">Atender</button>


                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

Views/Reception/Modulos.cshtml
@{
    ViewData["Title"] = "Modulos";
}

<div class="container">
    <div class="row">

    </div>
 
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                     <h3 class="card-title">Registrar Modulo</h3>
                    <form action="">
                        <div class="form-group">
                            <label for="Nombre"></label>
                            <input name="Nombre" class="form-control" placeholder="Ingrese nombre del modulo">
                        </div>
                        <div class="form-group">
                            <label for="Estado"></label>
                            <select name="" id="" name="Estado" class="form-select">
                                <option value="Habilitado">Habilitado</option>
                                <option value="nhabilitado">Inhabilitado</option>
                            </select>
                        </div><br>
                        <div class="form-group">
                        <button class="btn btn-success">Registrar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="d-flex">
                    <div class="col float-start">
                        <h1>Lista Modulos</h1>
                    </div>
                    <div class="col float-end">
                        
                    </div>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @{int countRecord = 1;}
                    @foreach(var item in Model){
                        <tr>
                            <td>@countRecord</td>
                            <td>@item.Id</td>
                            <td>@item.Nombre</td>
                            <td>@item.Estado</td>
                            <td><a href="" class="btn btn-sm btn-primary">Editar</a>
                                <a href="" class="btn btn-sm btn-danger">Deshabilitar</a>
                            </td>
                        </tr>
                        countRecord++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Reception/Turnos.cshtml
@{
    ViewData["Title"]="Turnos";
}

<div class="container">
    <div class="row">

    </div>
    <h1>Lista de Turnos</h1>
    <table class="table">
        <thead>
            <tr>
                <td>#</td>
                <th>Categoria</th>
                <th>Identificacion</th>
                <th>Turno</th>
                <th>Fecha Entrada</th>
           
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
             @{int countRecord = 1;}
            @foreach(var item in Model){
                <tr>
                    <td>@countRecord</td>
                    <td>@item.Categoria</td>
                    <td>@item.Identificacion</td>
                    <td>@item.Ficho</td>
                    <td>@item.FechaEntrada</td>
                    <td>@item.Estado</td>
                 
                    <td>
                        <a href="" class="btn btn-sm btn-primary">Detalles</a>
                        
                    </td>
                </tr>
                countRecord++;
            }
        </tbody>
    </table>
</div>

Views/Reception/Usuarios.cshtml
@{
    ViewData["Title"] = "Modulos";
}

<div class="container">
    <div class="row">

    </div>
 
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                     <h3 class="card-title">Registrar Usuario</h3>
                    <form action="">
                        <div class="form-group">
                            <label for="Nombre">Nombre</label>
                            <input name="Nombre" class="form-control" placeholder="Ingrese nombre del usaurio">
                        </div>
                         <div class="form-group">
                            <label for="Nombre">Correo:</label>
                            <input name="Correo" class="form-control" placeholder="Ingrese nombre del usaurio">
                        </div>
                        <div class="form-group">
                            <label for="Nombre">Contraseña:</label>
                            <input name="Password" class="form-control" placeholder="Ingrese nombre del usaurio">
                        </div>
                        <br>
                        <div class="form-group">
                        <button class="btn btn-success">Registrar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="d-flex">
                    <div class="col float-start">
                        <h1>Lista Usuarios</h1>
                    </div>
                    <div class="col float-end">
                        
                    </div>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Correo</th>
                        <th>Fecha Registro</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @{int countRecord = 1;}
                    @foreach(var item in Model){
                        <tr>
                            <td>@countRecord</td>
                            <td>@item.Id</td>
                            <td>@item.Nombre</td>
                            <td>@item.Correo</td>
                            <td>@item.FechaRegistro</td>
                            <td><a href="" class="btn btn-sm btn-primary">Editar</a>
                                <a href="" class="btn btn-sm btn-danger">Deshabilitar</a>
                            </td>
                        </tr>
                        countRecord++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>